-- =====================================================================
-- Mowe-Ibafo X Community Fitness Walk 2026
-- 0001 - Initial schema (fresh start, NO data migration)
--
-- Apply with:  supabase db push
--          or: npm run migrate   (from server/)
--
-- The auth schema is owned by Supabase Auth and already exists in every
-- Supabase project, so it is referenced here but never created.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Admins
-- One row per Supabase Auth user. The Auth UUID is the primary key.
-- ---------------------------------------------------------------------
create table if not exists public.admins (
  id          uuid primary key references auth.users (id) on delete cascade,
  legacy_id   integer null,
  name        text not null,
  email       text unique not null,
  role        text not null default 'admin' check (role in ('super', 'admin')),
  last_login  timestamptz null,
  created_at  timestamptz not null default now()
);

comment on table public.admins is
  'Administrator accounts. Backed by Supabase Auth; id = auth.users.id.';

-- ---------------------------------------------------------------------
-- Participants
--
-- participant_seq is the single source of truth for the human readable
-- id. It comes from a PostgreSQL sequence, never from MAX(id) + 1, so
-- concurrent registrations can never collide.
-- ---------------------------------------------------------------------
create sequence if not exists public.participant_seq start 1;

create table if not exists public.participants (
  id              bigint generated by default as identity primary key,
  participant_id  text        not null unique,
  participant_seq bigint     not null unique,
  full_name       text        not null,
  email           text        not null,
  phone           text        not null,
  photo_path      text        null,
  flyer_path      text        null,
  qr_path         text        null,
  status          text        not null default 'registered'
                    check (status in ('registered', 'verified', 'cancelled')),
  ip_address      text        null,
  registered_at   timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

comment on column public.participants.participant_seq is
  'Value from public.participant_seq (PostgreSQL sequence). Never MAX(id)+1.';

comment on column public.participants.participant_id is
  'Human readable id, for example MIWC2026-000001. Derived from participant_seq.';

create index if not exists participants_email_idx
  on public.participants (lower(email));

create index if not exists participants_phone_idx
  on public.participants (phone);

create index if not exists participants_status_idx
  on public.participants (status);

create index if not exists participants_registered_idx
  on public.participants (registered_at desc);

-- Duplicate email guard (case-insensitive) at the database level.
create unique index if not exists participants_email_unique_idx
  on public.participants (lower(email));


-- ---------------------------------------------------------------------
-- Event settings (singleton)
-- Two independent guards keep this to exactly one row: the primary key
-- default and a CHECK constraint that rejects any id other than 1.
-- ---------------------------------------------------------------------
create table if not exists public.event_settings (
  id                smallint primary key default 1 check (id = 1),
  event_name        text not null default 'Mowe-Ibafo X Community Fitness Walk 2026',
  description       text null,
  event_date        date null,
  event_time        time null,
  venue             text null,
  registration_open boolean not null default true,
  banner_path       text null,
  contact_email     text null,
  contact_phone     text null,
  whatsapp          text null,
  twitter_url       text null,
  instagram_url     text null,
  facebook_url      text null,
  updated_at        timestamptz not null default now(),
  constraint event_settings_singleton check (id = 1)
);

insert into public.event_settings (id, event_name, description, registration_open)
values (1,
        'Mowe-Ibafo X Community Fitness Walk 2026',
        'Promote healthy living, community unity, wellness, and active lifestyles.',
        true)
on conflict (id) do nothing;

-- ---------------------------------------------------------------------
-- Sponsors
-- ---------------------------------------------------------------------
create table if not exists public.sponsors (
  id             bigint generated by default as identity primary key,
  business_name  text not null,
  logo_path      text null,
  website_url    text null,
  whatsapp       text null,
  description    text null,
  priority       integer not null default 0,
  status         text not null default 'active' check (status in ('active', 'inactive')),
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create index if not exists sponsors_status_idx
  on public.sponsors (status);

create index if not exists sponsors_priority_idx
  on public.sponsors (priority desc, id asc);

-- ---------------------------------------------------------------------
-- Gallery
-- ---------------------------------------------------------------------
create table if not exists public.gallery (
  id           bigint generated by default as identity primary key,
  image_path   text not null,
  caption      text null,
  category     text not null default 'general',
  sort_order   integer not null default 0,
  status       text not null default 'active' check (status in ('active', 'inactive')),
  uploaded_at  timestamptz not null default now()
);

create index if not exists gallery_status_idx
  on public.gallery (status);

create index if not exists gallery_sort_order_idx
  on public.gallery (sort_order asc, id asc);

-- ---------------------------------------------------------------------
-- Contacts
-- ---------------------------------------------------------------------
create table if not exists public.contacts (
  id          bigint generated by default as identity primary key,
  name        text not null,
  email       text not null,
  phone       text null,
  subject     text not null,
  message     text not null,
  reply       text null,
  status      text not null default 'new'
                check (status in ('new', 'read', 'replied', 'resolved')),
  ip_address  text null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists contacts_status_idx
  on public.contacts (status);

create index if not exists contacts_email_idx
  on public.contacts (lower(email));

-- ---------------------------------------------------------------------
-- Email log
-- ---------------------------------------------------------------------
create table if not exists public.email_log (
  id         bigint generated by default as identity primary key,
  recipient  text not null,
  subject    text not null,
  status     text not null default 'sent' check (status in ('sent', 'failed')),
  sent_at    timestamptz not null default now()
);

create index if not exists email_log_status_idx
  on public.email_log (status);

create index if not exists email_log_sent_at_idx
  on public.email_log (sent_at desc);

-- ---------------------------------------------------------------------
-- updated_at triggers
-- ---------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $fn$
begin
  new.updated_at = now();
  return new;
end;
$fn$;

drop trigger if exists participants_set_updated_at on public.participants;
create trigger participants_set_updated_at
  before update on public.participants
  for each row execute function public.set_updated_at();

drop trigger if exists sponsors_set_updated_at on public.sponsors;
create trigger sponsors_set_updated_at
  before update on public.sponsors
  for each row execute function public.set_updated_at();

drop trigger if exists contacts_set_updated_at on public.contacts;
create trigger contacts_set_updated_at
  before update on public.contacts
  for each row execute function public.set_updated_at();


-- =====================================================================
-- Row Level Security
--
-- The Node backend uses the service role key, which bypasses RLS.
-- The React app NEVER talks to Supabase directly.
--
-- Everything therefore defaults to deny. The only public reads are
-- genuinely public data: active sponsors, open event settings and active
-- gallery images. admins, participants, contacts and email_log have no
-- policies at all, so they are unreachable from any client key.
-- =====================================================================
alter table public.admins         enable row level security;
alter table public.participants   enable row level security;
alter table public.event_settings enable row level security;
alter table public.sponsors       enable row level security;
alter table public.gallery        enable row level security;
alter table public.contacts       enable row level security;
alter table public.email_log      enable row level security;

drop policy if exists sponsors_public_read on public.sponsors;
create policy sponsors_public_read
  on public.sponsors
  for select
  to anon, authenticated
  using (status = 'active');

drop policy if exists event_settings_public_read on public.event_settings;
create policy event_settings_public_read
  on public.event_settings
  for select
  to anon, authenticated
  using (registration_open = true);

drop policy if exists gallery_public_read on public.gallery;
create policy gallery_public_read
  on public.gallery
  for select
  to anon, authenticated
  using (status = 'active');
